# [DEPRECATED] VuePress용 워크플로우 - VitePress로 마이그레이션됨
# 새로운 배포는 deploy.yml을 사용합니다.

name: build & deploy (DISABLED)

# 워크플로우 비활성화: VitePress로 마이그레이션 완료
on:
  workflow_dispatch: # 수동 실행만 가능
  # push:
  #   branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      # - name: install and build
      #   run: |
      #     npm install
      #     npm run build

      # - name: deploy build files
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   run: |
      #     cd docs/.vuepress/dist
      #     git config --global user.email "shockzinfinity@gmail.com"
      #     git config --global user.name "Jun Yu"
      #     git init
      #     git add -A
      #     git commit -m 'deploy with vuepress'
      #     git push -f https://${ACCESS_TOKEN}@github.com/shockzinfinity/shockzinfinity.github.io.git master
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: shockzinfinity/shockzinfinity.github.io
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn cache clean && yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
